//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.4-b18-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2005.06.20 at 10:22:56 EDT 
//


package jat.sim.xml.input;


/**
 * Java content class for Input element declaration.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/C:/Code/Jat/jat/xml/input/sim_input.xsd line 4)
 * <p>
 * <pre>
 * &lt;element name="Input">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element name="InitialState">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="Cartesian">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element name="x" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                               &lt;element name="y" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                               &lt;element name="z" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                               &lt;element name="xdot" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                               &lt;element name="ydot" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                               &lt;element name="zdot" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="Time">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="MJD" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                     &lt;element name="t0" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                     &lt;element name="tf" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                     &lt;element name="dt" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                     &lt;element name="thinning" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="Spacecraft">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="CR" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                     &lt;element name="cd" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                     &lt;element name="area" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                     &lt;element name="mass" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 */
public interface Input
    extends javax.xml.bind.Element, jat.sim.xml.input.InputType
{


}
