//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.4-b18-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2005.06.20 at 10:22:56 EDT 
//


package jat.sim.xml.input;

//import jat.spacecraft.Spacecraft;


/**
 * Java content class for anonymous complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/C:/Code/Jat/jat/xml/input/sim_input.xsd line 5)
 * <p>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="InitialState">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Cartesian">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="x" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                             &lt;element name="y" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                             &lt;element name="z" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                             &lt;element name="xdot" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                             &lt;element name="ydot" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                             &lt;element name="zdot" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Time">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="MJD" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                   &lt;element name="t0" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                   &lt;element name="tf" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                   &lt;element name="dt" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                   &lt;element name="thinning" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Spacecraft">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="CR" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                   &lt;element name="cd" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                   &lt;element name="area" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                   &lt;element name="mass" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface InputType {


    /**
     * Gets the value of the spacecraft property.
     * 
     * @return
     *     possible object is
     *     {@link jat.sim.xml.input.InputType.SpacecraftType}
     */
    SpacecraftType getSpacecraft();

    /**
     * Sets the value of the spacecraft property.
     * 
     * @param value
     *     allowed object is
     *     {@link jat.sim.xml.input.InputType.SpacecraftType}
     */
    void setSpacecraft(jat.sim.xml.input.InputType.SpacecraftType value);

    /**
     * Gets the value of the time property.
     * 
     * @return
     *     possible object is
     *     {@link jat.sim.xml.input.InputType.TimeType}
     */
    jat.sim.xml.input.InputType.TimeType getTime();

    /**
     * Sets the value of the time property.
     * 
     * @param value
     *     allowed object is
     *     {@link jat.sim.xml.input.InputType.TimeType}
     */
    void setTime(jat.sim.xml.input.InputType.TimeType value);

    /**
     * Gets the value of the initialState property.
     * 
     * @return
     *     possible object is
     *     {@link jat.sim.xml.input.InputType.InitialStateType}
     */
    jat.sim.xml.input.InputType.InitialStateType getInitialState();

    /**
     * Sets the value of the initialState property.
     * 
     * @param value
     *     allowed object is
     *     {@link jat.sim.xml.input.InputType.InitialStateType}
     */
    void setInitialState(jat.sim.xml.input.InputType.InitialStateType value);


    /**
     * Java content class for anonymous complex type.
     * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/C:/Code/Jat/jat/xml/input/sim_input.xsd line 8)
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Cartesian">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="x" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *                   &lt;element name="y" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *                   &lt;element name="z" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *                   &lt;element name="xdot" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *                   &lt;element name="ydot" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *                   &lt;element name="zdot" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     */
    public interface InitialStateType {


        /**
         * Gets the value of the cartesian property.
         * 
         * @return
         *     possible object is
         *     {@link jat.sim.xml.input.InputType.InitialStateType.CartesianType}
         */
        jat.sim.xml.input.InputType.InitialStateType.CartesianType getCartesian();

        /**
         * Sets the value of the cartesian property.
         * 
         * @param value
         *     allowed object is
         *     {@link jat.sim.xml.input.InputType.InitialStateType.CartesianType}
         */
        void setCartesian(jat.sim.xml.input.InputType.InitialStateType.CartesianType value);


        /**
         * Java content class for anonymous complex type.
         * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/C:/Code/Jat/jat/xml/input/sim_input.xsd line 11)
         * <p>
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="x" type="{http://www.w3.org/2001/XMLSchema}double"/>
         *         &lt;element name="y" type="{http://www.w3.org/2001/XMLSchema}double"/>
         *         &lt;element name="z" type="{http://www.w3.org/2001/XMLSchema}double"/>
         *         &lt;element name="xdot" type="{http://www.w3.org/2001/XMLSchema}double"/>
         *         &lt;element name="ydot" type="{http://www.w3.org/2001/XMLSchema}double"/>
         *         &lt;element name="zdot" type="{http://www.w3.org/2001/XMLSchema}double"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         */
        public interface CartesianType {


            /**
             * Gets the value of the zdot property.
             * 
             */
            double getZdot();

            /**
             * Sets the value of the zdot property.
             * 
             */
            void setZdot(double value);

            /**
             * Gets the value of the ydot property.
             * 
             */
            double getYdot();

            /**
             * Sets the value of the ydot property.
             * 
             */
            void setYdot(double value);

            /**
             * Gets the value of the z property.
             * 
             */
            double getZ();

            /**
             * Sets the value of the z property.
             * 
             */
            void setZ(double value);

            /**
             * Gets the value of the y property.
             * 
             */
            double getY();

            /**
             * Sets the value of the y property.
             * 
             */
            void setY(double value);

            /**
             * Gets the value of the xdot property.
             * 
             */
            double getXdot();

            /**
             * Sets the value of the xdot property.
             * 
             */
            void setXdot(double value);

            /**
             * Gets the value of the x property.
             * 
             */
            double getX();

            /**
             * Sets the value of the x property.
             * 
             */
            void setX(double value);

        }

    }


    /**
     * Java content class for anonymous complex type.
     * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/C:/Code/Jat/jat/xml/input/sim_input.xsd line 37)
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="CR" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *         &lt;element name="cd" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *         &lt;element name="area" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *         &lt;element name="mass" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     */
    public interface SpacecraftType {


        /**
         * Gets the value of the cd property.
         * 
         */
        double getCd();

        /**
         * Sets the value of the cd property.
         * 
         */
        void setCd(double value);

        /**
         * Gets the value of the cr property.
         * 
         */
        double getCR();

        /**
         * Sets the value of the cr property.
         * 
         */
        void setCR(double value);

        /**
         * Gets the value of the mass property.
         * 
         */
        double getMass();

        /**
         * Sets the value of the mass property.
         * 
         */
        void setMass(double value);

        /**
         * Gets the value of the area property.
         * 
         */
        double getArea();

        /**
         * Sets the value of the area property.
         * 
         */
        void setArea(double value);

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link java.lang.String}
         */
        java.lang.String getName();

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.lang.String}
         */
        void setName(java.lang.String value);

    }


    /**
     * Java content class for anonymous complex type.
     * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/C:/Code/Jat/jat/xml/input/sim_input.xsd line 26)
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="MJD" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *         &lt;element name="t0" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *         &lt;element name="tf" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *         &lt;element name="dt" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *         &lt;element name="thinning" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     */
    public interface TimeType {


        /**
         * Gets the value of the thinning property.
         * 
         */
        double getThinning();

        /**
         * Sets the value of the thinning property.
         * 
         */
        void setThinning(double value);

        /**
         * Gets the value of the dt property.
         * 
         */
        double getDt();

        /**
         * Sets the value of the dt property.
         * 
         */
        void setDt(double value);

        /**
         * Gets the value of the t0 property.
         * 
         */
        double getT0();

        /**
         * Sets the value of the t0 property.
         * 
         */
        void setT0(double value);

        /**
         * Gets the value of the mjd property.
         * 
         */
        double getMJD();

        /**
         * Sets the value of the mjd property.
         * 
         */
        void setMJD(double value);

        /**
         * Gets the value of the tf property.
         * 
         */
        double getTf();

        /**
         * Sets the value of the tf property.
         * 
         */
        void setTf(double value);

    }

}
