//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.4-b18-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2005.06.20 at 10:22:56 EDT 
//


package jat.sim.xml.input;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the jat.sim.xml.input package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
public class ObjectFactory
    extends jat.sim.xml.input.impl.runtime.DefaultJAXBContextImpl
{

    private static java.util.HashMap defaultImplementations = new java.util.HashMap(16, 0.75F);
    private static java.util.HashMap rootTagMap = new java.util.HashMap();
    public final static jat.sim.xml.input.impl.runtime.GrammarInfo grammarInfo = new jat.sim.xml.input.impl.runtime.GrammarInfoImpl(rootTagMap, defaultImplementations, (jat.sim.xml.input.ObjectFactory.class));
    public final static java.lang.Class version = (jat.sim.xml.input.impl.JAXBVersion.class);

    static {
        defaultImplementations.put((jat.sim.xml.input.Input.class), "jat.sim.xml.input.impl.InputImpl");
        defaultImplementations.put((jat.sim.xml.input.InputType.InitialStateType.class), "jat.sim.xml.input.impl.InputTypeImpl.InitialStateTypeImpl");
        defaultImplementations.put((jat.sim.xml.input.InputType.class), "jat.sim.xml.input.impl.InputTypeImpl");
        defaultImplementations.put((jat.sim.xml.input.InputType.SpacecraftType.class), "jat.sim.xml.input.impl.InputTypeImpl.SpacecraftTypeImpl");
        defaultImplementations.put((jat.sim.xml.input.InputType.TimeType.class), "jat.sim.xml.input.impl.InputTypeImpl.TimeTypeImpl");
        defaultImplementations.put((jat.sim.xml.input.InputType.InitialStateType.CartesianType.class), "jat.sim.xml.input.impl.InputTypeImpl.InitialStateTypeImpl.CartesianTypeImpl");
        rootTagMap.put(new javax.xml.namespace.QName("", "Input"), (jat.sim.xml.input.Input.class));
    }

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: jat.sim.xml.input
     * 
     */
    public ObjectFactory() {
        super(grammarInfo);
    }

    /**
     * Create an instance of the specified Java content interface.
     * 
     * @param javaContentInterface
     *     the Class object of the javacontent interface to instantiate
     * @return
     *     a new instance
     * @throws JAXBException
     *     if an error occurs
     */
    public java.lang.Object newInstance(java.lang.Class javaContentInterface)
        throws javax.xml.bind.JAXBException
    {
        return super.newInstance(javaContentInterface);
    }

    /**
     * Get the specified property. This method can only be
     * used to get provider specific properties.
     * Attempting to get an undefined property will result
     * in a PropertyException being thrown.
     * 
     * @param name
     *     the name of the property to retrieve
     * @return
     *     the value of the requested property
     * @throws PropertyException
     *     when there is an error retrieving the given property or value
     */
    public java.lang.Object getProperty(java.lang.String name)
        throws javax.xml.bind.PropertyException
    {
        return super.getProperty(name);
    }

    /**
     * Set the specified property. This method can only be
     * used to set provider specific properties.
     * Attempting to set an undefined property will result
     * in a PropertyException being thrown.
     * 
     * @param value
     *     the value of the property to be set
     * @param name
     *     the name of the property to retrieve
     * @throws PropertyException
     *     when there is an error processing the given property or value
     */
    public void setProperty(java.lang.String name, java.lang.Object value)
        throws javax.xml.bind.PropertyException
    {
        super.setProperty(name, value);
    }

    /**
     * Create an instance of Input
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public jat.sim.xml.input.Input createInput()
        throws javax.xml.bind.JAXBException
    {
        return new jat.sim.xml.input.impl.InputImpl();
    }

    /**
     * Create an instance of InputTypeInitialStateType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public jat.sim.xml.input.InputType.InitialStateType createInputTypeInitialStateType()
        throws javax.xml.bind.JAXBException
    {
        return new jat.sim.xml.input.impl.InputTypeImpl.InitialStateTypeImpl();
    }

    /**
     * Create an instance of InputType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public jat.sim.xml.input.InputType createInputType()
        throws javax.xml.bind.JAXBException
    {
        return new jat.sim.xml.input.impl.InputTypeImpl();
    }

    /**
     * Create an instance of InputTypeSpacecraftType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public jat.sim.xml.input.InputType.SpacecraftType createInputTypeSpacecraftType()
        throws javax.xml.bind.JAXBException
    {
        return new jat.sim.xml.input.impl.InputTypeImpl.SpacecraftTypeImpl();
    }

    /**
     * Create an instance of InputTypeTimeType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public jat.sim.xml.input.InputType.TimeType createInputTypeTimeType()
        throws javax.xml.bind.JAXBException
    {
        return new jat.sim.xml.input.impl.InputTypeImpl.TimeTypeImpl();
    }

    /**
     * Create an instance of InputTypeInitialStateTypeCartesianType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public jat.sim.xml.input.InputType.InitialStateType.CartesianType createInputTypeInitialStateTypeCartesianType()
        throws javax.xml.bind.JAXBException
    {
        return new jat.sim.xml.input.impl.InputTypeImpl.InitialStateTypeImpl.CartesianTypeImpl();
    }

}
